name: Lint-Proyecto IB

on: [push, pull_request]

jobs:
  lint:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Install dependencies
        working-directory: ./gestor-de-gastos-empresariales
        run: npm install
      - name: Run linter
        working-directory: ./gestor-de-gastos-empresariales
        run: npm run lint